CREATE TABLE IF NOT EXISTS pwa_devices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    device_id CHAR(36) NOT NULL UNIQUE,
    first_install DATETIME NOT NULL,
    last_seen DATETIME NOT NULL,
    install_count TINYINT UNSIGNED DEFAULT 1,
    platform VARCHAR(50),
    user_agent VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
